### ISSUE TITLE
Startup sequenz

### ISSUE THREAD

**Issue by an-klam** [BenediktSeidl/prpd#3]
Hallo,

ist die Hardware noch vorhanden oder evtl. noch mehr log files?
Ich wüsste gerne wie die Kommunikation aussieht während der WR an geht. 
Der WR Fragt mit 01 03 00 0B ja die ID des EM ab.
In meinem Fall lasse ich das EM mit 45 antworten aber es folgt keine weitere Abfrage...

**Comment by BenediktSeidl** [comment]
The powerrouter is no longer available, and it seems like i never recorded the communication after a reboot of the powerrouter. But one of the two EM24 is still in use: There were two of them installed, but currently only `02` is available.

I sent it this command:
```
02 03 00 0B 00 01 f5 fb
```
and it responded with
```
02 03 02 00 47 bc 76
```
So this one seems to response with `47`, not `45`. But I'm not sure if this is also the case with the `01` device. The datasheet of the EM24 mentions that values from `45` to `48` are possible. Have you tried others of this range?

What do you try to do? Replacing the EM24?

**Comment by an-klam** [comment]
47 would be indirect measurement.

![grafik](https://user-images.githubusercontent.com/75025337/189863819-1258b8ae-bb91-486f-9624-dc564078c5d1.png)


Yes im trying to replace the EM24, because i have already a SMA SHM2.0 and iobroker (with Modbus) is also there.

When the Nedap is starting, it asks for 3 EM Device ID 01,02 and 03
I think 01 is the Grid Sensor and 02 should be the Generation Sensor.
I dont know what 03 could be.

**Comment by BenediktSeidl** [comment]
As far as i know, only a single one is needed to make it work, and this should be `01` which was replaced in my setup.
Device ID `02` is needed to measure how much energy is consumed in the household, and should be optional. But I'm not sure if the device has to be configured to ignore `02`.
I can not remember any communication with device `03`.

Do you still have the EM24? Then you could try to tap the rs485 lines...

**Comment by an-klam** [comment]
Never had an EM24.
Got a Nedap for nearly free and tryiing to get it running.

Thanks for the help so far.
