### ISSUE TITLE
Question Registers

### ISSUE THREAD

**Issue by an-klam** [BenediktSeidl/prpd#4]
I do not know how else to contact, so an issue. :-)
Can you request the registers and tell me what are the values?
Current values, daily values, since startup or even the last X hours? 

![grafik](https://user-images.githubusercontent.com/75025337/193204502-a4f0b20e-4e83-4a38-aef8-00b6066d0e61.png)

**Comment by BenediktSeidl** [comment]
This is the total energy that went through the meter.
It's always incrementing, never decrementing. Basically the meter reading from a electricity meter.
