### ISSUE TITLE
hardware battery

### ISSUE THREAD

**Issue by an-klam** [BenediktSeidl/prpd#5]
Hi!
Managed to emulate the EM24.
Next project: emulate a Battery for the nedap.

Do you still use the Battery? 
Maybee you can lookup a few things in the canbus of the battery for me.

**Comment by BenediktSeidl** [comment]
sorry, i don't have the battery anymore and did not read the battery communication between the inverter and the battery, so i can not help you here. good luck!
would be cool if you could release the result of your research, so other can build upon them :-)
